### ISSUE TITLE
Can't load plugin on Spigot server

### ISSUE THREAD

**Issue by shrx** [WillPall/MobRepellent#6]
```
[10:13:22 ERROR]: Could not load 'plugins/MobRepellent-0.7.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: class mobrepellent.MobRepellent overrides final method getLogger.()Ljava/util/logging/Logger;
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:290) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:742) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:631) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.VerifyError: class mobrepellent.MobRepellent overrides final method getLogger.()Ljava/util/logging/Logger;
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_75]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_75]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_75]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_75]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
        at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-081dfa5-5e6c347]
        ... 14 more
```

**Comment by shrx** [comment]
Found a fork that fixes the error: https://github.com/amoliski/MobRepellent
